name: End-to-End Testing
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.2 # use the explicit version number
        with:
          working-directory: src/main/
          # build: npm run build
          build: npm ci
          start: npm start
          runTests: npx cypress run
          # spec: src/main/cypress/**/*
