name: 'JS Doc Creations'
on: push
jobs:
  js-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1
        with:
           source_dir: ./src/main/js
           recurse: true
           output_dir: ./out